Vagrant.configure("2") do |config|

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box="shekeriev/centos-stream-9"
        jenkins.vm.hostname = "jenkins.home1.lab"
        jenkins.vm.network "private_network", ip: "192.168.99.101"
        jenkins.vm.provision "shell", path: "linux-finisher.sh"
        jenkins.vm.provision "shell", path: "docker-setup.sh"
        jenkins.vm.provision "shell", path: "jenkins-setup.sh"
        jenkins.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "3072"]
        end
    end

end
