Vagrant.configure("2") do |config|

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

    config.vm.define "docker1" do |docker1|
        docker1.vm.box="shekeriev/centos-stream-9"
        docker1.vm.hostname = "docker1.home1.lab"
        docker1.vm.network "private_network", ip: "192.168.99.101"
        docker1.vm.provision "shell", path: "docker-setup.sh"
        docker1.vm.provision "shell", path: "linux-finisher.sh"
        docker1.vm.provision "shell", path: "swarm-manager-setup.sh"
        docker1.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1536"]
        end
    end

    config.vm.define "docker2" do |docker2|
        docker2.vm.box="shekeriev/centos-stream-9"
        docker2.vm.hostname = "docker2.home1.lab"
        docker2.vm.network "private_network", ip: "192.168.99.102"
        docker2.vm.provision "shell", path: "docker-setup.sh"
        docker2.vm.provision "shell", path: "linux-finisher.sh"
        docker2.vm.provision "shell", path: "swarm-worker-setup.sh"
        docker2.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1536"]
        end
    end
    
    config.vm.define "docker3" do |docker3|
        docker3.vm.box="shekeriev/centos-stream-9"
        docker3.vm.hostname = "docker3.home1.lab"
        docker3.vm.network "private_network", ip: "192.168.99.103"
        docker3.vm.provision "shell", path: "docker-setup.sh"
        docker3.vm.provision "shell", path: "linux-finisher.sh"
        docker3.vm.provision "shell", path: "swarm-worker-setup.sh"
        docker3.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1536"]
        end
    end

    # TODO Research for a cleanup process on vagrant destroy. Delete init.log & worker-token.temp

end