version: "3.8"
services:
    web:
        image: demiro/bgapp-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/devops-playground/bgapp/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: demiro/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
